remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Paulo Abalos]
description: [ - Resume]
logo: /images/picture1.jpg

<h3 id="header-3">Header 3</h3>
<p>Minimal is a theme for GitHub Pages.</p>

